version: "3.8"

services:
  postgresdb:
    env_file:
      - ./.env
    image: postgres:latest
    volumes:
      - db-data:/home/inatec/db/data
    networks:
      - inatec-network
    container_name: "postgresdb"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
networks:
    inatec-network:
volumes:
    db-data: